resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/2256fd727c5f92e6218afdcf8cddf6e01c4a9dcd/snapshot.yaml

packages:
  - .
  - test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ff5fd5f33849be8a826506c34e5b0278f267f804
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: bd978263ab884c4b27c940fcfe2d1ee8604afc5f
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-chain
    commit: fa7d892c596ccd54e852236126fc30a6e5ff0a9b
    subdirs:
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 965b32be3361b2ed404e1e58a6fb3cf525d3a26c
    subdirs:
      - specs/semantics/hs
      - specs/ledger/hs
      - specs/chain/hs

  - git: https://github.com/input-output-hk/cardano-mainnet-mirror
    commit: 0232971dddd5cd235c5a0c18d7b4f342a887276f

  - sequence-0.9.8
  - tasty-hedgehog-0.2.0.0

  # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 71b5637085a04259d25f84b6e1a8f7a54d981409

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 0c31ff69e28b8a955a5147c03cd9471307b3f349

  - ekg-0.4.0.15
  - ekg-json-0.1.0.6
  - time-units-1.0.0

nix:
  shell-file: scripts/nix/stack-shell.nix
