resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/ff5fd5f33849be8a826506c34e5b0278f267f804/snapshot.yaml

packages:
  - .
  - test

extra-deps:
  - git: https://github.com/input-output-hk/cardano-prelude
    commit: ff5fd5f33849be8a826506c34e5b0278f267f804
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 2f33cbf9101dfee1cb488271ec96e210329eec96
    subdirs:
      - binary
      - binary/test

nix:
  shell-file: ../scripts/nix/stack-shell.nix
